import re

def format_assistant_response(text: str) -> str:
    """
    Cleans and formats the markdown response generated by the assistant
    to ensure it looks good in the Streamlit UI.
    """
    if not text:
        return ""
    
    # Ensure there is a space after header hashes
    text = re.sub(r'^(#+)([^#\s])', r'\1 \2', text, flags=re.MULTILINE)
    
    # Clean up trailing whitespaces
    text = "\n".join([line.rstrip() for line in text.split("\n")])
    
    # Ensure double newlines before headers for better spacing
    text = re.sub(r'([^\n])\n(#{1,6}\s)', r'\1\n\n\2', text)
    
    return text
